### PR TITLE
Add the ui package

### PR DESCRIPTION
**Pull request by eaburns**

### CODE REVIEW

**Comment by eaburns** [comment]
Hey Steve, what do I have to do to get this working on OSX?
There's no sdl-config on OSX is there? That would be too convenient, right?

**Comment by mccoyst** [comment]
There's rarely a need to use pkg-config or sdl-config for SDL, IMGO. Just slap [the LDFLAGS stuff from velour/ui](https://github.com/velour/ui/blob/master/cflags.go) into a cgo comment and include SDL/SDL.h. (Ignore the includes in the CLFAGS ones; I didn't need to do that.)

**Comment by eaburns** [comment]
There's a bug closing the ui.
I need to fix that in addition to your sdl-config changes.

**Comment by eaburns** [comment]
PTAL.

**Pull request merged**
