### PR TITLE
Cleanup temp files in tests

### PR DESCRIPTION
**Pull request by mccoyst**
Be sure to clean things up when done with them and not later, to avoid "too many open files" errors

### CODE REVIEW

**Comment by mccoyst** [comment]
I don't know what gok.sh's problem is, since it doesn't say and I can't run it on my machine since I don't have `tempfile`! Plain old go test works, though:

    % go test ./...
    ok  	github.com/eaburns/T/edit	0.090s
    ok  	github.com/eaburns/T/edit/runes	0.116s
    ok  	github.com/eaburns/T/re1	0.010s
    ?   	github.com/eaburns/T/ui	[no test files]
    ?   	github.com/eaburns/T/ui/play	[no test files]
    ?   	github.com/eaburns/T/ui/sdl2	[no test files]

**Comment by chrissexton** [comment]
:-1: ;)

**Comment by mccoyst** [comment]
Ah, it was indeed my formatting. About to push a fix.

**Comment by mccoyst** [comment]
OK, that worked, so I'll rebase and destroy all evidence it ever happened!

**Comment by eaburns** [comment]
I don't understand what the ambiguous comment is about. The script says what it's doing at each step. Here's the output that I see:
$ ./gok.sh 
Formatting
Vetting
Testing
Linting

If the error is:
 * Under the word "Formatting" then you need to run goimports.
 * Under the word "Vetting" then you need to fix a govet error.
 * Under the word "Testing" then you broke a test.
 * Under the word "Linting" then you need to either fix or silence a linter warning.

But, I'll admit, I'm not the best at writing portable shell scripts (apparently, they aren't even portable across Linuxes). Maybe it's time to rewrite this as ok.go with `// -build`. Then anyone (even on Windows!) can run it with go run.

**Comment by eaburns** [comment]
I also wonder if we should use a function and defer instead. That way, on panic, the files still clean up.

**Comment by mccoyst** [comment]
Do you mean a function as the loop bodies? Makes sense, although it looked like we were OK for panics in those spots.

**Comment by eaburns** [comment]
Yeah. That's what I meant. But I didn't look into it much. If it seems OK
to you then it is OK to me.

**Pull request merged**
