### PR TITLE
Use re1.Regexp instead of string.

### PR DESCRIPTION
**Pull request by eaburns**
This pushes the re1.Compile error handling up to the user in various cases.

### CODE REVIEW

**Comment by eaburns** [comment]
Don't merge this yet. Substitute also needs special handling if given a literal regexp :-(

**Comment by eaburns** [comment]
PTAL.

**Comment by eaburns** [comment]
Don't worry about the coverage decrease.

**Comment by eaburns** [comment]
Still not right. If it was compiled literal, it doesn't necessarily compile as non-literal...

**Comment by eaburns** [comment]
The issue is that we need a way to make a string out of whatever we are given. Currently, there is only a way to make a string out of forward, non-literal regular expressions. I'm going to introduce new syntax: a ! delimiter means literal, a ? delimiter means reverse, and to handle a reverse literal, simply reverse the string.

**Comment by eaburns** [comment]
Reverse literal can't work that way. It has to run the regexp from the end if the range to the beginning. Simply reversing the string won't do that. Instead, use interrobang to mean reverse literal — how convenient!

**Comment by eaburns** [comment]
@mccoyst, let me describe the issue that I'm having in some detail.

I am trying to fix #141.

#### Some background

Edits and Addresses can be created using functions like Change and Regexp and Line, without any error return. Particularly for Addresses, this lets you chain-build them: `Regexp(...).Plus(Line(...)).To(End.Minus(Rune(...)))`. If you had to check error returns then building addresses that way would be awful:
```
re, err := Regexp(...)
if err != nil { do something }
l, err := Line(...)
if err != nil { do something }
tmp := re.Plus(l)
...
```
(In the future, with the Block Edit, { and } in sam/acme parlance, you will be able to chain edits too.)

So far this hasn't been a problem; we were able to make all inputs to all Edits and Addresses valid so that errors were not possible. For example, negative Line numbers are equivalent to `Dot.Minus(Line(...))`; Non-positive Undo counts are interpreted as 1; non-positive Substitution skip counts are interpreted as 1; any rune is a valid mark; etc. 

I realized, however, that regexps are an issue. They can have errors. Consider `(abc` --- an un-closed paren. What do we do with these invalid regular expressions? Currently, we do nothing. They are just held as strings and the error is reported when you try to use the bad expression with `Editor.Do` or similar. Doesn't sound too bad, but now what about Address.String? It has to output the string representation of the Address. It implements fmt.Stringer, which doesn't allow for an error return. Currently it just outputs a bad regular expression. This seems totally bogus to me.

Enter #141. If we used re1.Regexp instead of strings for regular expressions, the problem goes away. To get the re1.Regexp in the first place, the user has to compile and check the errors. By the time that it's passed to the edit package, all errors have been checked. It also fits better with the idea that the edit package holds *machine* representations of Edits and Addresses. Regular expressions strings are for humans; compiled regular expressions are for machines. The machine forms should hold the compilerd Regexp.

#### Some foreground

Everything so far gets us up to the point of implementing this PR. But now I am encountering issues with this PR itself. Namely, re1.Regexp is more expressive than Regexp Addresses or Substitution Edits.

Every Address and Edit must be convertible to a string to satisfy it's String method. When constructing Addresses and Edits using a re1.Regexp, this may not be possible! re1.Regexps can be compiled forward or reverse, and either literal or non-literal. Regexp Addresses can be forward or reverse, but are always non-literal. Substitution Edits are always forward, non-literal. How can I emit a string representation of this address:
```
re, err := re1.Compile("*+?)([]", Options{Literal: true}) // Note that it's Literal.
if err != nil { panic(err) }
a := Regexp(re)
whatIsThis := a.String()
```
There is no way to represent a literal Regexp Address, so there is no such string. Simply emitting `/*+?)([]/` is clearly wrong. In fact it'll be an error when parsed.

#### Possible solutions

I though about some possible solutions, but I am not sure which is the best. Perhaps some other solution that I haven't though of yet is best.

##### Leave well enough alone

The first option is to just ditch this PR and leave things alone. The String method will emit malformed regexps, which will be interpreted as errors when parsed. This is simple, but it annoys me.

I don't like the current state of affairs. The edit package doesn't truly know the re1 syntax or understand delimiters. These are independent of the edit package; the are the responsibility of the re1 package and could actually change. So, edit requires *all* regexps to be *needlessly* delimited. Otherwise it wouldn't know how to *add* delimiters when outputting to a string. For example, it requires `Regexp("/abc/")` instead of simply `Regexp("abc")`.

I suppose this is solvable, by adding `re1.Delimited(delim rune, nonDelimited string) (delimited string)`, which I've already written for this PR, but it's not exported. Something to consider.

##### Make the string representations more expressive

Another alternative is to use re1.Regexp instead of strings, as in this PR, but to make the String representation of Addresses and Edits more expressive so that it can handle all possible inputs. Regexp Addresses already support reverse match with the ? delimiter. If Substitute is given a reverse-compiled regexp, then the delimiter ? could mean to do a reverse match within the range: `4,5s2?abc?xyz?` substitutes the second from the last occurrence `abc` with `xyz` within the 4th and 5th lines.

We could use ! for literals. I did this for `re1.Must` in this PR. So, `!*()?!` would be the address of the literal string `*()?`. However, you can have reverse, literal regexps. My first thought was to simply call strings.Reverse (which actually doesn't exist, but you get the point) on the *literal* regexp string to reverse it. But that's not right. It's not enough to reverse the regexp, we have to actually run it on the address range in reverse too. So, it occurred to me that my favorite punctuation mark actually, per chance, combines both ? and !. So the interrobang, ‽, could be the delimiter for a reverse, literal regexp. Cute, but this seems a bit awful to me.

##### Meet in the middle

We could meet in the middle by reducing the expressiveness of re1 and increasing the expressiveness of edit. To do this, I could remove Literal as on option to re1. The Regexp Address already handles reverse, so it would just be a matter of adding reverse support to Substitute (a very annoying implementation challenge, but so be it). However, this makes me sad, because it would be very convenient to use literal Regexp Addresses to implement Look.

**Comment by mccoyst** [comment]
My initial, possibly-conflicting thoughts:

1. Ditch the Literal option from re1. Don't worry about not reusing the code; a literal search is trivial & doesn't need to be done through a regular expression.
2. Export re1.Delimited.
3. Make an exception for edit.Sub and have it return an error for reversed regexps (and whatever else isn't supported). Reverse substitution is too hard to understand — just look at your example. Not a worthy feature, IMGO. Sub won't be chainable, but would it really be much more convenient? Imagine a potential `Sub(r0, "x").Sub(r1, "y").Sub(r2, "z")`. It would still have to be preceded by 

```
r0, err := re1.Compile(…)
if err != nil { … }
r1, err := re1.Compile(...)
if err != nil { … }
r2, err := re1.Compile(…)
if err != nil { … }

e := Sub(r0, "x").Sub(r1, "y").Sub(r2, "z")
```

**Comment by eaburns** [comment]
Thanks for taking a look. I get the impression that you don't really like the options either. Some questions about your points 1-3:
 1. A bit sad. I guess it may be trivial to implement it, but it just adds more to the API. There now must be a new Address type which is the same as Regexp, but always literal. Perhaps it would be called Look?
 2. Since you think that Delimited should be unexported, does that mean that you think that I should stick with strings instead of re1.Regexp? If so, why bother deleting Literal? If so, what to do about malformed regexp strings in String methods?
 3. What about creating a Substitute edit by simply using the exported Substitute type? How would we return the error? Should I unexport that type and make a function for it?

**Comment by eaburns** [comment]
BTW, chaining edits wouldn't be `Sub().Sub().Sub()`, but more like `Block(All, Sub(), Sub(), Sub())`

**Comment by mccoyst** [comment]
1. Sounds good.
2. Right, it'd only be a factor if you gave up on using re1.Regexps. In that case, regarding malformed strings, I would say let garbage in be garbage out.
3. Yeah, unexport that, add a function with five args?

**Comment by eaburns** [comment]
To recap what we discussed in IRC:
> I guess that I'm leaning toward not using it, letting garbage in be garbage out, and exporting Delimited.

What do you think about using the delimiter ! to mean a literal match for the Regexp Address. That would obviate the need for a special Look Address (which, by the way, would need its own special syntax anyway). There is already precedence for the Regexp address using a delimiter to change the compilation options (? means reverse).

**Comment by mccoyst** [comment]
Sounds good. I don't think there is anything else I'd rather ! be used for in this context.

**Comment by eaburns** [comment]
Thanks a lot. I'll do it.

**Comment by eaburns** [comment]
I updated #141 to document our decision. I'm going to close this. I'll open a new one for the new changes.

**Pull request closed without merging**
