### PR TITLE
ui/text: optimizations

### PR DESCRIPTION
**Pull request by eaburns**

### CODE REVIEW

**Comment by eaburns** [comment]
What do you think about the 'intern Styles' change? I don't think it's strictly necessary. Also, there is a lot of allocation because spans copy the []byte into a string so the user can modify the given []byte without breaking the spans. I _could_ intern those too, but I really don't want to. That makes me think that I shouldn't bother with styles either.

**Comment by eaburns** [comment]
I have another (possibly big) improvement.

**Comment by eaburns** [comment]
How about now? Everything is cached and freelisted, and whatever.

**Comment by eaburns** [comment]
What do you think? Is all of the free listing and caching overkill? add1 was showing up in the mem profile, but, honestly, it still is. The first round of allocations even seems to put it there.

**Comment by eaburns** [comment]
The problem that brought up all of this ugly caching is that resizing the window in my new UI demo was slow and laggy as hell. I found a simple and quite obvious solution to it. The solution is to not redraw the window at all-out-full-speed, but just check whether we need to redraw every 20ms. With that, resizing looks great. I'm going to close this PR. I'll open a new one with only the worthwhile changes picked out of this.

**Comment by mccoyst** [comment]
:+1:

**Pull request closed without merging**
