### PR TITLE
Add <, >, and | edits

### PR DESCRIPTION
**Pull request by eaburns**

### CODE REVIEW

**Comment by eaburns** [comment]
@mccoyst, mind double checking too?

**Comment by mccoyst** [comment]
The default shell and the associated flag which takes the command as an argument (e.g. `/bin/sh` and `-c`) are platform-specific, but they can be the same for everything but windows.

**Comment by mccoyst** [comment]
Windows is either `cmd.exe` or `powershell.exe` (if you want to accept that XP is dead).

**Comment by eaburns** [comment]
What's power shell's equivalent of -c?

**Comment by mccoyst** [comment]
I don't remember; I sent it to you in an email before, though

**Comment by eaburns** [comment]
Let's not worry about Windows for this first pass. Geoff, feel free to merge this when you are happy with it. Then we'll open a bug to get it working on Windows.

**Comment by eaburns** [comment]
OK. Thanks. I also Googled it, I think it's -Command.

**Pull request merged**
