### PR TITLE
Add io-style Reader, Writer, Copy functions to runes.

### LINKED ISSUE #83: Implement proper bufferSource insert.
It shouldn't copy to an intermediate buffer. It should copy directly from the cache of one buffer to that of another. This way, it doesn't have to hold more than cache size runes in memory at a time.

### PR DESCRIPTION
**Pull request by eaburns**
This simplifies some of runes.Buffer, but makes some of the calling code a bit more verbose.
However, it has various benefits:
1. It gets rid of the need for edit.source, which was ugly.
2. It fixes #83 in an elegant way.
3. It will easily support <, >, and | via a to-be-written runes.UTF8Writer and runes.RuneReaderReader.
4. It will make it easy to read from HTTP request bodies and to write to HTTP response bodies without extra copying.

### CODE REVIEW

**Comment by eaburns** [comment]
I'm assigning this to @leGoof, as he's actively helping with T, but, @mccoyst, would you take a look too?

I need to apologize.  The first commit copies runes.go -> buffer.go and runes_test.go -> buffer_test.go, and creates a new runes.go and runes_test.go. Git doesn't track the changes across the move, so the diff is terrible. It's impossible to look at the overall diff and tell how buffer.go changed from the original runes.go. You may have to look at the individual commits. I tried to clean them up into nice logical steps. So hopefully it's not too bad.

If I were to do this again, knowing how bad git is at tracking changes across files moves, I would have made all of the changes in the original files and then done one commit at the end to rename things.

**Comment by eaburns** [comment]
Found a bug. One second.

**Comment by eaburns** [comment]
OK. PTAL.

**Comment by leGoof** [comment]
From what I can tell, it all looks fine. I'm going to wait to pull til @mccoyst has a chance to look at it though.

**Comment by mccoyst** [comment]
Do it

**Pull request merged**
